path_to_class: learning.data_curator.DataCurator
config:
  # batch_size: 64
  batch_size: 24
  dataset_paths:
    - path: ???
  datasets_root: ''
  # num_dataloader_workers: 8
  num_dataloader_workers: 0 # [Debug] TypeError: h5py objects cannot be pickled
  random_dev_subset: 1
  random_train_subset: 1
  sample_with_replacement: False
